providers = ["node"]

[phases.setup]
nixpkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --include=dev", "cd client && npm install --include=dev"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = ["node", "server/index.js"]
